‘Investigate the types of variables involved, their likely distributions, and their relationships with each other’ – how will I do this? Hopefully as I research I will stumble across an idea.

‘Synthesise/simulate a data set as closely matching their properties as possible’ – I think this should be possible once I have completed some research and established some real data on the topic.

‘Detail your research and implement the simulation in a Jupyter notebook – the data set itself can simply be displayed in an output cell within the notebook’ – having become familiar with Jupyter notebook in our last assignment for this module I feel confident that I should be able to complete this. I am hoping for some feedback on the assignment prior to handing in this project so I can implement the feedback here.

I should research this phenomenon and see what types of real data has been collected on it, and then synthesise data for this project. I should use Python to model and synthesise such data.

1.	Phenomenon = the adoption of dogs or puppies from animal shelters.
2.	Variable = perhaps the breed of the dog/puppy.
3.	I should try to come up with the equivalent of the examples Ian has provided in the project example (number of hours study, number of logins to Moodle, previous qualifications), perhaps this could be compared to how well trained the dog is, the amount of previous owners the dog has had and how many times it has been placed for adoption by different owners, and age of the dog/puppy.

I should investigate how these impact the likelihood of the dog/puppy being successfully adopted.


##### Dr. Ian McLoughlin's example which I based my work on;
The hours and grade variables will be non-negative real number with two decimal places, logins will be a non-zero integer and qual will be a categorical variable with four possible values: none, bachelors, masters, or phd. After some online research, I find that full-time post-graduate students study on average four hours per week with a standard deviation of a quarter of an hour and that a normal distribution is an acceptable model of such a variable. Likewise, I investigate the other four variables, and I also look at the relationships between the variables. I devise an algorithm (or method) to generate such a data set, simulating values of the four variables for two-hundred students. I detail all this work in my notebook, and then I add some code in to generate a data set with those properties.

##### Marking Scheme;

25% Research Investigation of the data set as demonstrated by references, background information, and approach. 

25% Development Clear, well-written, and efficient code with appropriate comments. 

25% Consistency Good planning and pragmatic attitude to work as evidenced by commit history. 

25% Documentation Concise descriptions and plots of variables in the data set.

##### Advice for students; 
•	Your git commit history should be extensive – I will try to ensure this.


##### Brainstorming based on Dr. Ian McLoughlin's 27/11/2018:

Performance of students studying a 10 credit module = successfully rehomed dogs in a shelter

Variables;

Grade = Successful rehoming/ non-successful rehoming

 - Hours = Breed of dog/puppy

 - Logins = amount of previous owners the dog has had / age of the dog/puppy

 - Qualifications = how well trained the dog is

The 3 above variables should be closely related to the successful/non-successful rehoming of the dog.

After brainstorming the variables I realised some of the ideas I had come up with were not numbers (e.g. breed of dog/puppy). I decided to try allocating a figure to approximately 5 breeds, something like;

1 – German Shepherd

2 – Labrador

3 – Collie

4 – Greyhound

5 – Mixed breed

I will try this approach and see if it works.

The same scenario occurs for another variable I had chosen – how well trained the dog is. I decided to allocate levels of training from 1 to 3;

1 – Well trained

2 – Somewhat trained

3 – Not trained at all

These are all non-negative real numbers.

*To do tomorrow 28/11/2018:*

Now that I have a fair idea what real-world phenomenon I would like to simulate data for, I need to become more familiar with the numpy.random package which I will use to model and synthesise the data using Python.

*02/12/2018*

At this point I had decided what I would like my data set to represent.

To do: Model & synthesise the data using Python – numpy.random package.

There should be at least one-hundred data points across four different variables.

Create a synthesised data set.

Devise an algorithm (or method) to generate my data set.

Detail this work in my notebook.

Add some code to generate a data set with those properties.

Review the numpy.random package videos on Moodle.

The the numpy.random package is used for generating random data in Python, which is exactly what I want to do.

I reviewed the following videos;
1.	Introduction to numpy.random
2.	Introduction to numpy. I also checked out http://www.numpy.org/.
3.	Setting up the numpy.random repo

*03.12.2018*
I reviewed the following videos;
4.	Setting up the numpy.random repo
5.	Numpy.random docs
6.	Rand function video
7.	Distributions video

I initially thought that I would need to compile my synthesised data somewhere. I then realised that numpy.random will do this for me – it will generate arrays of numbers for me, so I don’t need to compose them myself.

To launch jupyter notebook on my system I must; CMD > Anaconda Prompt > jupyter notebook

I received the results of my assignment which I had completed for this module in November by email from Dr Ian McLoughlin on 04th December. 
I reviewed the constructive feedback carefully and tried to apply it to this project.

### Dr. Ian McLoughlin’s feedback;

- Research:

Your submission was of a reasonable standard in this category.
You might consider further developing the following in future submissions:
Make sure to inform yourself of other people's approaches to problems like the one set out in the assignment brief. In your submission, you might summarise your findings and then make an informed decision as to your approach to the problem. You can provide evidence that you carried out this research by documenting it within your submission.
Try to break the overall assignment into smaller components. Research each of these components, and then consider how they might fit together to provide an overall solution.

- Development

Your submission was of a reasonable standard in this category.
You might consider further developing the following in future submissions:
Make sure you demonstrate your competence in programming, including an ability to search, read and understand documentation.
You code must work and files should be named appropriately with correct filename extensions.

- Consistency

Your submission was of a reasonable standard in this category.
You might consider further developing the following in future submissions:
Make sure you manage your own learning and development, including time management and organisational skills, and make this evident in your submissions.
You should reflect on previous projects you have completed and have the foresight to see common potential issues coming down the tracks during your project.

- Documentation

Your submission was of a reasonable standard in this category.
You might consider further developing the following in future submissions:
Your documentation should provide descriptions and instructions for understanding your submission.
All code should be commented. Usually each statement requires a comment and a preamble is required at the beginning of every file.

I was unsure which simple random data code to use for this purpose, so I researched some different options from https://docs.scipy.org/doc/numpy-1.15.1/reference/routines.random.html and decided that for my purposes and the dataset I wish to create, the following would be the most suitable; numpy.random.shuffle

numpy.random.shuffle can be used to modify a sequence in-place by shuffling its contents.

This function only shuffles the array along the first axis of a multi-dimensional array. The order of sub-arrays is changed but their contents remains the same (Reference: https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.random.shuffle.html#numpy.random.shuffle)


While reviewing the 'rand function' video on Moodle, I knew the example shown was exactly what I needed for this project. I visited the webpage https://docs.scipy.org/doc/numpy-1.15.1/reference/routines.random.html. In the video Dr. Ian McLoughlin mentioned that if you wish to generate random data for everyday purposes the ‘Simple random data’ section can be utilised. 
I selected 'rand' from the 'Simple random data' section. I decided to play around with the code provided in 'rand' and see whether this woud be suitable code for the purposes of this project.

In [1]:
np.random.rand(3,2)


NameError: name 'np' is not defined

The above error indicates I need to import the numpy package before I can use numpy. I followed Dr. Ian McLoughlin's guidance and inserted and ran the below code, followed by the 'rand' code;

In [2]:
import numpy as np

In [3]:
np.random.rand(3,2)

array([[0.54623784, 0.9897952 ],
       [0.59975932, 0.25249016],
       [0.83709015, 0.98169146]])

We can see that after I import the numpy package and run the code the error no longer appears.

In [4]:
import numpy as np

In [5]:
np.random.rand(10)

array([0.64612552, 0.86492938, 0.80634593, 0.71676204, 0.14416379,
       0.12771556, 0.59059287, 0.13190038, 0.20472569, 0.55305608])

Instead of (3,2), I tried the figure 10, as I want my dataset to represent whole numbers rather than numbers with decimal places.

Unfortunately, decimal numbers still appeared. 

How do I create rows and columns representing whole numbers which would fit my choices for the dataset I wish to create?

I revisited the webpage https://docs.scipy.org/doc/numpy-1.15.1/reference/routines.random.html and researched the different options. I came accross one which I felt may fit my needs so I decided to try it out;

In [7]:
np.random.randint(2, size=10)

array([1, 0, 0, 0, 1, 1, 0, 0, 1, 1])

This is known as 'numpy.random.randint' according to the webpage, and returns 'random integers from low (inclusive) to high (exclusive).' I decided to use this code.

In [8]:
np.random.randint(2, size=100)

array([0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0,
       1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0,
       0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1])

However, I quickly realised it did not fit my purposes as shown when I tried out the above code with 100 replacing 10. It seemed it only produced figures 1 and 0, which would not be suitable for my dataset. I tried another code:

In [9]:
np.random.randint(7, size=100)

array([0, 0, 6, 5, 2, 2, 5, 3, 2, 2, 3, 1, 5, 1, 5, 5, 3, 6, 3, 4, 3, 6,
       6, 6, 3, 4, 3, 0, 0, 4, 2, 3, 0, 1, 1, 0, 0, 3, 4, 3, 0, 5, 2, 1,
       6, 3, 6, 6, 0, 3, 1, 0, 1, 6, 5, 2, 4, 1, 2, 2, 5, 4, 1, 6, 2, 2,
       2, 3, 3, 3, 1, 3, 1, 2, 0, 1, 6, 3, 4, 0, 4, 4, 5, 5, 4, 4, 6, 4,
       2, 1, 1, 0, 0, 3, 4, 3, 6, 4, 3, 5])

I replaced 2 with 7, and the results were much more fitting, as shown above. I tested this out with one of my chosen variables – breed of dog;
1 – German Shepherd
2 – Labrador
3 – Collie
4 – Greyhound
5 – Mixed breed

5 breeds. 


In [10]:
np.random.randint(5, size=100)

array([4, 4, 2, 4, 4, 3, 2, 1, 4, 1, 0, 3, 2, 3, 3, 1, 0, 1, 0, 4, 0, 2,
       3, 3, 4, 0, 2, 3, 1, 3, 3, 3, 0, 4, 4, 2, 0, 4, 1, 4, 1, 2, 1, 1,
       2, 0, 2, 1, 1, 2, 3, 3, 2, 3, 4, 2, 1, 2, 4, 4, 0, 4, 2, 2, 3, 2,
       2, 2, 1, 0, 3, 1, 3, 1, 0, 1, 2, 3, 0, 4, 4, 3, 1, 4, 4, 2, 3, 0,
       0, 0, 0, 3, 3, 4, 2, 3, 1, 0, 0, 2])

I was not so happy with the first set of results - out of 100 dogs, 5 breeds, there are 20 greyhounds, 22 labradors, 21 collies, 18 german shepherds and no mixed breeeds. I counted the amount of times each figure appeared, and that's how I discovered how many of each breed of dog made up the total of 100 dogs. Not only was it unrealistic that there would be lots of pedigree dogs and no mixed breed dogs in a dog shelter for addoption, there were also 18 0's in the dataset, which I could not attribute to any of my 5 chosen breeds. I decided to play around with the code to try and rectify this;

In [11]:
np.random.randint(6, size=100)

array([2, 2, 2, 0, 0, 0, 2, 0, 1, 5, 4, 0, 0, 3, 1, 4, 3, 1, 1, 2, 5, 2,
       1, 3, 5, 5, 4, 1, 5, 2, 5, 0, 4, 4, 2, 3, 5, 1, 1, 4, 2, 2, 4, 2,
       3, 0, 0, 0, 3, 3, 1, 2, 2, 0, 2, 3, 1, 1, 3, 3, 3, 2, 5, 1, 5, 5,
       1, 0, 3, 5, 4, 3, 4, 2, 1, 3, 5, 0, 2, 1, 2, 0, 4, 5, 2, 4, 2, 3,
       5, 2, 0, 3, 5, 5, 2, 3, 5, 0, 5, 3])

Although replacing the 5 with a 6 yielded more realistic results (there were 18 mixed breeds out of 100 dogs recorded using this code), there were still a lot of 0's which I wanted to eradicate. I decided instead to let 0 represent one of the breeds, and to stick with the original code. My new variables would be represented by; 

0 - German Shepherd 

1 - Labrador

2 - Collie 

3 - Greyhound 

4 - Mixed breed;

In [12]:
np.random.randint(5, size=100)

array([2, 4, 4, 1, 4, 0, 3, 1, 1, 2, 3, 4, 4, 2, 4, 1, 3, 0, 1, 1, 4, 4,
       1, 4, 4, 3, 0, 1, 3, 4, 0, 3, 3, 2, 1, 3, 3, 3, 4, 1, 2, 4, 4, 1,
       3, 2, 2, 2, 0, 2, 0, 3, 1, 3, 3, 3, 3, 1, 2, 0, 2, 4, 1, 0, 4, 3,
       0, 3, 4, 2, 1, 3, 4, 4, 0, 4, 0, 4, 4, 2, 0, 3, 0, 1, 0, 2, 0, 1,
       2, 2, 3, 1, 0, 0, 2, 0, 0, 4, 1, 0])

This ensured all 5 breeds were included. In my dataset of 100 dogs in total there are now;

German shepherds (represented by the figure '0') - 20

Labradors - (represented by the figure '1') - 19

Collies - (represented by the figure '2') - 17

Greyhounds - (represented by the figure '3') - 21

Mixed breeds - (represented by the figure '4') - 23

Total: 100

These fgures coincidentally reflect the breeds fairly accurately based on the research I completed - greyhounds are the pure bred dog most likely to be surrendered to shelters, and there are always lots of mixed breeds.


In [13]:
![Screenshot](GermanShepherd.jpg)

'[Screenshot]' is not recognized as an internal or external command,
operable program or batch file.


In [14]:
![Image of German Shepherd](https://https://goo.gl/images/dYD6rc)

'[Image' is not recognized as an internal or external command,
operable program or batch file.


In [15]:
![Image of German Shepherd](https://gfnc1kn6pi-flywheel.netdna-ssl.com/wp-content/uploads/2018/07/your-female-german-shepherd-SC-long.jpg)

'[Image' is not recognized as an internal or external command,
operable program or batch file.


![Image of German Shepherd](https://gfnc1kn6pi-flywheel.netdna-ssl.com/wp-content/uploads/2018/07/your-female-german-shepherd-SC-long.jpg)

As you can see from my failed attempts above I had some difficulty adding an image to this Jupyter notebook initially, I then ralised the cell needed to be a markdown cell as opposed to a code cell, and once I made this amendment the required image of a German Shepherd dog which I sourced on Google Images appeared correctly.

I knew I needed to generate information which could be attributed to the other variables. I decided to explore some other options starting with numpy.random.choice;

In [1]:
np.random.choice (5,3)

NameError: name 'np' is not defined

In [2]:
import numpy as np

In [3]:
np.random.choice (5,3)

array([3, 2, 2])

After running the above code I decided I could use this in relation to the variable I had chosen regarding the dog's levels of training from 1 to 3 (1 – Well trained, 2 – Somewhat trained, and 3 – Not trained at all). I knew I would need to use (3,5), 3 being the 3 different levels of training, and 5 being the 5 different dog breeds. I ran the code;

In [4]:
np.random.choice (3, 5)

array([0, 1, 0, 0, 0])

The results above did not turn out how I anticipated, the figure 0 was one of the results, and I only wanted figure 1, 2 and 3 to be generated, so I decided to try something different;

In [5]:
np.random.choice (4, 5)

array([1, 2, 0, 2, 3])

Still 0 was present. 

In [6]:
np.random.choice (5, 5)

array([3, 0, 0, 0, 2])

And again, 0 was present. I decided to change my original plan - instead of 1, 2 and 3 representing the dog's levels of training I decided to use 0, 1 and 2 (0 – Well trained, 1 – Somewhat trained, and 2 – Not trained at all). 
I ran the code;


In [7]:
np.random.choice (3, 5)

array([2, 2, 1, 2, 1])

I decided to let the results represent the following;

The first result represents the first breed of dog in the list (German shepherd) Training level: 2 - Not trained at all. This indicates one of the German shepherds is not trained at all.

2 - Labrador - Not trained at all

1 - Collie - Somewhat trained

2 - Greyhound - Not trained at all

1 - Mixed breed - Somewhat trained



I needed to run a code which would synthesise the level of trainings per dog out of 100 dogs;

In [8]:
np.random.choice (3, 100)

array([0, 0, 0, 2, 2, 2, 0, 1, 2, 0, 2, 1, 2, 1, 2, 0, 2, 0, 0, 0, 2, 1,
       0, 0, 0, 0, 2, 2, 1, 2, 0, 2, 2, 0, 0, 1, 2, 0, 0, 1, 1, 1, 0, 2,
       1, 2, 2, 1, 2, 2, 1, 2, 0, 2, 0, 2, 2, 0, 0, 0, 0, 2, 0, 1, 1, 2,
       2, 2, 0, 0, 2, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 2, 2, 0, 1, 2, 2,
       2, 2, 0, 0, 0, 2, 2, 0, 0, 0, 2, 0])

Dog 1 which is a German shepherd according to my first data set has a training level of 0 = Well trained.

Based on my research it is likely that the pedigree dogs who are well trained are most likely to be adopted.


##### To do:	
- 12.11.2018 – 18.11.2018: Review project video and instructions. Create repository and submit link. COMPLETED.

- 19.11.2018 – 25.11.2018: Finish reviewing all videos. Review and adhere to marking scheme. COMPLETED.

- 26.11.2018 – 02.12.2018: Commence project. Pick a phenomenon and research it. Create the dataset. COMPLETED.

- 03.12.2018 – 09.12.2018: Complete project - COMPLETED.

- 10.12.2018 – 13.12.2018: Submit project - COMPLETED.

#### Minimum standard 
The minimum standard for this project is a git repository containing a README, a gitignore file and a Jupyter notebook. 
The README need only contain an explanation of what is contained in the repository and how to run the Jupyter notebook. 
Your notebook should contain the main body of work and should list all references used in completing the project. 
A good submission will be clearly organised and contain concise explanations of the particularities of the data set. 
The analysis contained within the notebook will be well conceived, interesting, and well researched. 
Note that part of this project is about the use of Jupyter notebooks and so you should make use of all the functionality available in the software including images, links, code and plots. 
You may use any Python libraries that you wish, whether they have been discussed in class or not.


#### References

- https://www.aspca.org
- MADRA Website - http://www.madra.ie/
- ISPCA Website - https://www.ispca.ie
- Department of Environment, Community and Local Government Website –
- https://www.thejournal.ie
- https://www.irishtimes.com
- Dog control report 2017
- https://drcd.gov.ie
- http://www.numpy.org/ 
- https://jupyter.readthedocs.io/en/latest/running.html#running
- Docs.scipy.org/doc/numpy
- Videos provided by Dr. Ian McLoughlin (Moodle)